source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'rails', '=6.0.2.1'
gem 'puma', '=3.11'
gem 'sass-rails', '=5.1.0'
gem 'uglifier', '=4.2.0'
gem 'coffee-rails', '=4.2.2'
gem 'turbolinks', '=5.2.1'
gem 'jbuilder', '2.9.1'
gem 'bootsnap', '=1.4.5', require: false
gem 'sassc', '2.2.1'
gem 'webpacker', '4.2.2'
